# Import libs

In [6]:
import pandas as pd
import numpy as np
import sys, os
sys.path.append("../..")

from data.CloudData import DrillingData

# Import data

In [11]:
DrillingData().get()

,GR,Resist_short,Resist_long,DrillingSpeed,LITHOLOGY,CPs
time,,,,,,
1970-01-01 00:00:00,8.864000,125.248,0.134,35.063,0.0,0.0
1970-01-01 00:00:01,9.511000,254.847,0.134,35.297,0.0,0.0
1970-01-01 00:00:02,10.332000,426.608,0.134,35.546,0.0,0.0
1970-01-01 00:00:03,9.988000,402.661,0.134,35.832,0.0,0.0
1970-01-01 00:00:04,9.001000,244.039,0.134,36.132,0.0,0.0
...,...,...,...,...,...,...
1970-01-01 04:25:23,38.689846,50.265,448.802,26.497,3.0,0.0
1970-01-01 04:25:24,38.689846,50.265,448.802,26.422,3.0,0.0
1970-01-01 04:25:25,38.689846,50.265,448.802,26.285,3.0,0.0
1970-01-01 04:25:26,38.689846,50.265,448.802,26.114,3.0,0.0
1970-01-01 04:25:27,38.689846,50.265,448.802,25.858,3.0,0.0

In [ ]:
DrillingData("A684G").get()