# Import libs

In [1]:
import pandas as pd
import numpy as np
import sys, os
sys.path.append("../..")

from data.CloudData import DrillingData
from data.DataTransformers import CloudDataTransformer

# Import data

In [2]:
DrillingData().get()

              GR  Resist_short  Resist_long  DrillingSpeed  LITHOLOGY  CPs
0       8.864000       125.248        0.134         35.063        0.0  0.0
1       9.511000       254.847        0.134         35.297        0.0  0.0
2      10.332000       426.608        0.134         35.546        0.0  0.0
3       9.988000       402.661        0.134         35.832        0.0  0.0
4       9.001000       244.039        0.134         36.132        0.0  0.0
...          ...           ...          ...            ...        ...  ...
15923  38.689846        50.265      448.802         26.497        3.0  0.0
15924  38.689846        50.265      448.802         26.422        3.0  0.0
15925  38.689846        50.265      448.802         26.285        3.0  0.0
15926  38.689846        50.265      448.802         26.114        3.0  0.0
15927  38.689846        50.265      448.802         25.858        3.0  0.0

[15928 rows x 6 columns]

In [3]:
DrillingData("xxxAA684G").get()

,Unnamed: 0,Unnamed: 1,m,v/v,v/v.1,uR/h,v/v.2,v/v.3,v/v.4,mD,...,m/hr,ohmm,ohmm.1,ohmm.2,ohmm.3,ohmm.4,ohmm.5,ohmm.6,unitless.2,m.1
0,xxxAA684G,PTRNZHG_A,2974.1,0.508686,-9999.0,-9999.000,-9999.0,-9999.0,0.144000,-9999.00,...,-9999.000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,9.210000,0.126706,-9999.000000,-9999.0,-9999.000000
1,xxxAA684G,PTRNZHG_A,2974.2,0.508686,-9999.0,-9999.000,-9999.0,-9999.0,0.144000,-9999.00,...,-9999.000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,9.210000,0.126706,-9999.000000,-9999.0,-9999.000000
2,xxxAA684G,PTRNZHG_A,2974.3,0.508686,-9999.0,-9999.000,-9999.0,-9999.0,0.144000,-9999.00,...,-9999.000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,9.210000,0.126706,-9999.000000,-9999.0,-9999.000000
3,xxxAA684G,PTRNZHG_A,2974.4,0.508686,-9999.0,-9999.000,-9999.0,-9999.0,0.144000,-9999.00,...,-9999.000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,9.210000,0.126706,-9999.000000,-9999.0,-9999.000000
4,xxxAA684G,PTRNZHG_A,2974.5,0.508686,-9999.0,-9999.000,-9999.0,-9999.0,0.144000,-9999.00,...,-9999.000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,9.210000,0.126706,-9999.000000,-9999.0,-9999.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11140,xxxAA684G,PTRNZHG_A,4088.1,0.020558,0.0,125.715,-9999.0,0.0,0.040035,0.01,...,53.630,9.683760,8.039845,8.429146,7.789839,9.411731,0.126455,0.126452,-9999.0,2576.684969
11141,xxxAA684G,PTRNZHG_A,4088.2,0.020558,0.0,126.480,-9999.0,0.0,0.040035,0.01,...,73.350,9.530000,7.990000,8.310000,7.740000,9.411731,0.126455,0.126452,-9999.0,2576.689355
11142,xxxAA684G,PTRNZHG_A,4088.3,0.020558,0.0,122.645,-9999.0,0.0,0.040035,0.01,...,55.030,9.474839,7.979993,8.294987,7.740000,9.411731,0.126455,0.126452,-9999.0,2576.693738
11143,xxxAA684G,PTRNZHG_A,4088.4,0.020558,0.0,118.810,-9999.0,0.0,0.040035,0.01,...,36.710,9.419999,7.970000,8.280000,7.740000,9.411731,0.126455,0.126452,-9999.0,2576.698122
11144,xxxAA684G,PTRNZHG_A,4088.5,-9999.000000,0.0,122.200,-9999.0,-9999.0,-9999.000000,-9999.00,...,45.625,9.404988,7.979994,8.269994,7.729993,-9999.000000,-9999.000000,0.126452,-9999.0,2576.702502

In [4]:
transformed_aa684g = CloudDataTransformer(DrillingData("xxxAA684G").get(), "xxxAA684G").transform()

In [5]:
transformed_aa684g.LITHOLOGY.unique()

array([nan,  2.,  5.,  3.,  6.])

In [6]:
transformed_aa684g

,GR,Resist_short,Resist_long,DrillingSpeed,LITHOLOGY,CPs
time,,,,,,
1970-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,1
1970-01-01 00:00:01,NaN,NaN,NaN,NaN,NaN,1
1970-01-01 00:00:02,NaN,NaN,NaN,NaN,NaN,1
1970-01-01 00:00:03,NaN,NaN,NaN,NaN,NaN,1
1970-01-01 00:00:04,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...
1970-01-01 03:05:40,125.715,9.683760,0.126452,53.630,2.0,0
1970-01-01 03:05:41,126.480,9.530000,0.126452,73.350,2.0,0
1970-01-01 03:05:42,122.645,9.474839,0.126452,55.030,2.0,0
1970-01-01 03:05:43,118.810,9.419999,0.126452,36.710,2.0,1
1970-01-01 03:05:44,122.200,9.404988,0.126452,45.625,NaN,0